### ISSUE TITLE
terraform doesn't generate a kubectl config file

### ISSUE THREAD

**Issue by MartinaRuocco** [SurrealAI/cloudwise#2]
I'm following the tutorial from [SurrealAI](https://github.com/SurrealAI/surreal/blob/master/docs/surreal_kube_gke.md) and I am stuck at step 5. "Install GPU Drivers". 
After executing the command:
`kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/stable/nvidia-driver-installer/cos/daemonset-preloaded.yaml`
I get this error: 
```
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config
To view or setup config directly use the 'config' command.
```

In my opinion, this is due to the fact that the cloudwise output file (<cluster_name>.tf.json) is not correct/updated and, as a result, terraform does NOT create a kubectl config file.
In fact, the kubectl config file should be automatically created at cluster creation time, as described in the [documentation of kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/):

> In order for kubectl to find and access a Kubernetes cluster, it needs a kubeconfig file, which is created automatically when you create a cluster using kube-up.sh or successfully deploy a Minikube cluster. By default, kubectl configuration is located at ~/.kube/config.

I am trying to follow the [terraform documentation](https://www.terraform.io/docs/providers/kubernetes/guides/getting-started.html) to understand how to create a kube config file using the terraform cluster creation, but I am quite confused about the solution.
I think I should be modifying the provider section of the .tf.json file, but I am not sure.

**Comment by LinxiFan** [comment]
Thanks for your issue! We are not maintaining anymore, so it's likely that there are new version incompatibilities over the last two years. We are sorry for the inconvenience.

**Comment by LinxiFan** [comment]
It isn't maintained anymore, thanks for your understanding!
